### ISSUE TITLE
LocationNavigate.dll depends on msvcp80.dll and msvcr80.dll

### ISSUE THREAD

**Issue by d0vgan** [JetNpp/LocationNavigate#1]
At first, thank you for the pre-built version of LocationNavigate.dll!
Soon I realized that it does not work without msvcp80.dll and msvcr80.dll since it depends on them.
So I took the source code from https://sourceforge.net/projects/locationnav/files/Source/ and built the LocationNavigate.dll from the sources with the runtime libraries statically linked.
However, I am not sure whether you did some modifications to the original code or not, and thus I am not sure if the original source code requires some improvements/patches/etc. Could you shed some light on this?

**Comment by JetMeta** [comment]
Not add any new feature except change parameter of SetWindowLong from GWL_WNDPROC to GWLP_WNDPROC. Hope this helps. Have fun.
